version: '3'

services:
  # Windows with Docker Desktop WSL 2 backend
  # The vm.max_map_count setting must be set in the docker-desktop container:
  # wsl -d docker-desktop
  # sysctl -w vm.max_map_count=262144
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
  

  nats:
    image: nats:2.1
    container_name: nats
    ports:
      - "4222:4222"
    networks:
      - bus-dev-utils

volumes:
  mongo:
  postgres:
  redis:
  mysql:

networks:
  bus-dev-utils:
    name: bus-dev-utils
