version: "3.3"

services:

  smart-challenge:
    build:
      context: .
      dockerfile: Dockerfile
    image: smart-challenge
    container_name: smart-challenge
    env_file: docker-compose.env
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
      - modules:/app/node_modules

volumes:
  data:
  modules:

networks:
  default:
    external:
      name: bus-dev-utils
